apiVersion: apps/v1
kind: Deployment
metadata:
  name: messenger
spec:
  selector:
    matchLabels:
      app: messenger
    replicas: 2
    template:
      metadata:
        labels:
          app: messenger
      spec:
        containers:
          - name: messenger
            image: grekas/messenger
            ports:
              - containerPort: 5174
